version: '3'
services:
  db:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  web:
    build: ./bank-account-prototype
    ports:
      - "8080:8080"
    depends_on:
      - db
